name: Build Binaries

on:
  push:
    tags: 'v*'
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare builds
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Create build dir
      run: |
        mkdir build/
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'
    - name: Install deps
      run: go get ./...

  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        NAME="dotm-$GOOS-$GOARCH"
        if [[ "$GOOS" == "windows" ]]; then NAME="$NAME.exe"; fi
        go build -o "build/$NAME" -v ./...

  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/*
        token: ${{ secrets.ACCESS_TOKEN }}
